# "service" is the name of this project. This will also be added to your AWS resource names.
service: ce6-sls-aldindc
frameworkVersion: "4"

provider:
  name: aws
  stage: prod
  runtime: nodejs20.x
  region: ap-southeast-1

functions:
  aldindc:
    handler: delta.hello
    events:
      - httpApi:
          path: /aldindc
          method: get
plugins:
  - serverless-offline
